# Generated by Django 4.2.1 on 2023-06-02 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='out_of_production',
        ),
        migrations.AddField(
            model_name='product',
            name='in_production',
            field=models.BooleanField(default=True, verbose_name='In Production'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+375(29)XXX-XX-XX'", regex='\\+375\\(29\\)\\d{3}-\\d{2}-\\d{2}')], verbose_name='Phone Number'),
        ),
    ]
