# Generated by Django 4.2.1 on 2023-09-14 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0006_order_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_name', models.CharField(max_length=255, verbose_name='Clients Name')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating')),
                ('date', models.DateField(verbose_name='Release Date')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
