# Generated by Django 4.2.1 on 2023-09-14 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0008_alter_review_clients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Release Date'),
        ),
    ]
