# Generated by Django 4.2.5 on 2023-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0013_product_image_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=500, null=True, verbose_name='Text'),
        ),
    ]
