# Generated by Django 4.2.5 on 2023-11-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0014_alter_article_summary_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('date', models.DateField(null=True, verbose_name='Release Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.CharField(max_length=500, verbose_name='Image')),
                ('promo_code', models.TextField(max_length=15, null=True, verbose_name='Promo code')),
            ],
        ),
    ]
