# Generated by Django 4.2.5 on 2023-11-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0016_alter_coupon_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount'),
        ),
    ]
